# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: deploy-shiny

on: [push,pull_request]

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-r@v2
      
      - name: Install cURL Headers
        if: runner.os == 'Linux'
        run: sudo apt-get install libcurl4-openssl-dev
        
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::shiny
            any::rsconnect
            
      #- name: Install shiny
      #  run: |
      #    install.packages(c("shiny", "rsconnect"))
      #  shell: Rscript {0}      
      
      - name: Push to shiny.io
        run: |
          rsconnect::setAccountInfo(name="bokov", token="${{secrets.SHINYAPPS_TOKEN}}", secret="${{secrets.SHINYAPPS_SECRET}}")
          rsconnect::deployApp(appDir=file.path(getwd(),"BexarCOVID_6202"),appName = "SP22TSCI6202_ci")
        shell: Rscript {0}
